version: '3.8'

services:
  db: 
    environment:
      POSTGRES_PASSWORD: "SomeHa!dPas1wod"
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    depends_on:
      - db
    build: ./AnovaTask.API
    ports:
      - "8080:8080"
